// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./autobase.js')
  await import('./autobee.js')
  await import('./client.js')
  await import('./core.js')
  await import('./gc.js')
  await import('./metrics.js')
  await import('./notifications.js')
  await import('./trusted-peers.js')

  test.resume()
}
