// This runner is auto-generated by Brittle

await runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./autobase.js'))
  await test.load(import.meta.resolve('./autobee.js'))
  await test.load(import.meta.resolve('./client.js'))
  await test.load(import.meta.resolve('./core.js'))
  await test.load(import.meta.resolve('./gc.js'))
  await test.load(import.meta.resolve('./metrics.js'))
  await test.load(import.meta.resolve('./muxer-request.js'))
  await test.load(import.meta.resolve('./notifications.js'))
  await test.load(import.meta.resolve('./trusted-peers.js'))
  await test.load(import.meta.resolve('./subprocess-kill.js'))

  test.resume()
}
