name: Mine Tests
on:
  workflow_dispatch:
    inputs:
      os:
        description: Platforms to mine on
        type: string
        default: '["ubuntu-latest", "windows-latest"]'
      files:
        description: Test files to mine
        type: string
        default: '["test/autobase.js", "test/autobee.js", "test/client.js", "test/core.js", "test/gc.js", "test/metrics.js", "test/notifications.js", "test/trusted-peers.js"]'
  pull_request:
    paths:
      - .github/workflows/mine.yml
permissions:
  contents: read
jobs:
  mine:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(inputs.os || '["windows-latest"]') }}
        file: ${{ fromJSON(inputs.files || '["test/autobase.js", "test/autobee.js", "test/client.js", "test/core.js", "test/gc.js", "test/metrics.js", "test/notifications.js", "test/trusted-peers.js"]') }}
    name: Mine ${{ matrix.file }} (${{ matrix.os }})
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - shell: bash
        env:
          FILE: ${{ matrix.file }}
        run: timeout 10m ./node_modules/.bin/brittle-bare -m 8 "$FILE" || [ $? -eq 124 ]
